### ISSUE TITLE
Crashes if HOME env var is not set

### ISSUE THREAD

**Issue by c24w** [hoegaarden/pgpass#14]
[`getFileName()`](https://github.com/hoegaarden/pgpass/blob/d1ccb8e99efcea8dce6036fd06ee9f48a85b96d0/lib/helper.js#L56-L64) assumes `process.env.HOME` is set, in linux, which may not always be the case (e.g. in AWS Lambda functions).  This means `undefined` is passed to `path.join` and it's not happy about that.

**Comment by hoegaarden** [comment]
Hey @c24w & @mctrp ,

Sorry, I somehow missed that issue. I will try to fix that issue asap. Meanwhile I think there are a couple of workarounds:
- set `$HOME`
- set `$PGPASSFILE`
- set `$PGPASSWORD`

Sorry about the loooooong delay.

**Comment by mctrp** [comment]
@c24w I was setting the `PGPASSWORD` variable but not the global `process.env.PGPASSWORD` which is what node-postgress is looking for as you described. 

In the end I used the connectionString approach, as the Programmatic approach seems to be ignored when using a nodejs 10.x AWS Lambda function. It keeps defaulting to the environmental variables, even though they are not set.

No worries @hoegaarden :D.

**Comment by ferrants** [comment]
I encountered this as well. Made this PR to not check this environment variable if it's unset
https://github.com/hoegaarden/pgpass/pull/16

**Comment by rathboma** [comment]
Also having this issue in an Electron app when no password is provided. The pr seems pretty simple and solves the issue. @ferrants maybe also do the same check for the windows APPDATA variable?

**Comment by hoegaarden** [comment]
Addressed in #17
