### ISSUE TITLE
FileHandles don't get closed

### ISSUE THREAD

**Issue by hkocam** [hoegaarden/pgpass#6]
Hi,

i'm experiencing something related to this issue:
https://github.com/nodejs/node-v0.x-archive/issues/6041

After a while my log get filled with this:
```
WARNING: error on reading file: Error: EMFILE: too many open files, open '.pgpass'
Failed to prune sessions: password authentication failed for user "XXXXXXX"
```

It looks like filehandles not getting closed in lib/helper.js line 121.
If i add 
`stream.destroy();`
before calling the cb everything works fine.

I'm using pg 4.4 and connect-pg-simple as session-handler in express4.
pg searches the client-pool for idle clients every 30 seconds.and 
connect-pg-simple deletes expired sessions from the db every minute.
on this test-system there is no other activity other than the session pruning 
and everytime the pruning process runs theirs no active client in the pool and a new connection get opened and pgpass opens a new filehandle to the pgpass-file 

as a workaround i lowered the session-pruning-timeout below the idlesessiontimeout in pg
i hope this makes sense 

kind regards
hakan kocaman

**Comment by hoegaarden** [comment]
Hey,

Thanks for the bug report!
To you perhaps have a (minimal) code example which triggers this bug?
Can you also provide all the versions (node, pg, pg-natvie, ...) you are using?

**Comment by giratikanon** [comment]
I had this happen with Sequelize, which uses `pgpass`. Eventually thousands of `~/.pgpass` files were left open and crashed my server app.

If you use Sequelize with a user that has a password, but do not provide the password directly, Sequelize will use `pgpass` to look for a `.pgpass` file. 

Each time you make a query, another `.pgpass` file is opened for the life of the script, which can be forever if it's a server.

Example Node Script:

```node
var Sequelize = require('sequelize');

// assumes the `postgres` user has a password, 
// and the local database requires a password
var database = new Sequelize("postgres", "postgres", "", {
  host: "localhost",
  dialect: "postgres",
  logging: false
});

database.query("SELECT 1").then(function() {
  console.log("queried");
});

setTimeout(function() {
 // keep the process running a while so you can run `lsof` in another window
}, 10000);
```

Use `lsof` to see the open `.pgpass` files:

```
lsof | grep pgpass
```

**Comment by hoegaarden** [comment]
Sorry for the delay, I will try to tend to that ASAP.

**Comment by mthrok** [comment]
Hi @hoegaarden 

I came across this issue with `restify` and `node-postgres`, so tried your patch in https://github.com/hoegaarden/pgpass/tree/issue/6 and it resolved this. Can you release it?

Thanks,

**Comment by hoegaarden** [comment]
Hey @mthrok 

[issue/#6](/hoegaarden/pgpass/tree/issue/6) has been merged and `pgpass` has been released already, pull request for `node-postgres` [was opened](https://github.com/brianc/node-postgres/pull/1098).

Thanks for verifying and letting me know..

Bye!
